### ISSUE TITLE
Unclear instructions.

### ISSUE THREAD

**Issue by demiurgeQuantified** [loblao/libpandadna#14]
I'm pretty sure this goes in the issues area:
This part, make absolutely no sense to me:

"*Almost done. Now, in Visual Studio:
- Add all panda3d directories to include/lib path (and python dirs too!)*"

...What? I honestly don't get what I'm supposed to be doing here. Where? What directories? I don't see any in VS.

**Comment by Teku16** [comment]
Where are there instructions?

**Comment by Loudrob** [comment]
There aren't any. Figure it out.

**Comment by Teku16** [comment]
I was referencing the instructions that maroon56 was talking about..
