### ISSUE TITLE
easy way to convert xml file to dna?

### ISSUE THREAD

**Issue by mgracer48** [loblao/libpandadna#20]
i want to know if there is a way to do this using a tool instead of doing it manually

**Comment by zachgates7** [comment]
libpandadna isn't really for that @mgracer48

**Comment by mgracer48** [comment]
:(

**Comment by zachgates7** [comment]
Message me on Skype (@zach.gates9) and I'd be more than willing to help you out. @mgracer48

**Comment by loblao** [comment]
I'm not aware of any tools that can do this. You can however write some XML reader in Python (see XML parsing in Python docs) to parse it and output DNA files. Any pull requests implementing this are welcome.
