### ISSUE TITLE
(OSX) Unable to find library while interrogating

### ISSUE THREAD

**Issue by Loudrob** [loblao/libpandadna#23]
When interrogation starts after building the files, this is what happens.

Linking CXX shared library liblibpandadna.dylib
Interrogate
/Developer/Panda3D
/Users/username/libpandadna/src
Interrogating base
dyld: Library not loaded: libp3dtool.1.9.dylib
  Referenced from: /Developer/Panda3D/bin/interrogate
  Reason: image not found
src/run_interrogate: line 12:  1736 Trace/BPT trap: 5       $PANDA_DIR/bin/interrogate -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus -fnames -string -refcount -assert -S $PANDA_DIR/include/parser-inc -S $PANDA_DIR/include -I $PANDA_DIR/include -I$SRC_DIR/suit -I$SRC_DIR/base -I$SRC_DIR/components -srcdir $SRC_DIR/$MODULE -oc $SRC_DIR/base_igate.cxx -od $SRC_DIR/$MODULE.in -python-native -DCPPPARSER -D__STDC__=1 -D__cplusplus -D__inline -longlong __int64 -D_X86_ -DWIN32_VC -DWIN32 -D_WIN32 -module libpandadna -library $MODULE -Dvolatile= DNAStorage.h DNALoader.h
Interrogating suit
dyld: Library not loaded: libp3dtool.1.9.dylib
  Referenced from: /Developer/Panda3D/bin/interrogate
  Reason: image not found
src/run_interrogate: line 18:  1737 Trace/BPT trap: 5       $PANDA_DIR/bin/interrogate -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus -fnames -string -refcount -assert -S $PANDA_DIR/include/parser-inc -S $PANDA_DIR/include -I $PANDA_DIR/include -I$SRC_DIR/suit -I$SRC_DIR/base -I$SRC_DIR/components -srcdir $SRC_DIR/$MODULE -oc $SRC_DIR/suit_igate.cxx -od $SRC_DIR/$MODULE.in -python-native -DCPPPARSER -D__STDC__=1 -D__cplusplus -D__inline -longlong __int64 -D_X86_ -DWIN32_VC -DWIN32 -D_WIN32 -module libpandadna -library $MODULE -Dvolatile= DNASuitPoint.h DNASuitPath.h DNASuitEdge.h SuitLeg.h SuitLegList.h
Interrogating components
dyld: Library not loaded: libp3dtool.1.9.dylib
  Referenced from: /Developer/Panda3D/bin/interrogate
  Reason: image not found
src/run_interrogate: line 24:  1738 Trace/BPT trap: 5       $PANDA_DIR/bin/interrogate -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus -fnames -string -refcount -assert -S $PANDA_DIR/include/parser-inc -S $PANDA_DIR/include -I $PANDA_DIR/include -I$SRC_DIR/suit -I$SRC_DIR/base -I$SRC_DIR/components -srcdir $SRC_DIR/$MODULE -oc $SRC_DIR/components_igate.cxx -od $SRC_DIR/$MODULE.in -python-native -DCPPPARSER -D__STDC__=1 -D__cplusplus -D__inline -longlong __int64 -D_X86_ -DWIN32_VC -DWIN32 -D_WIN32 -module libpandadna -library $MODULE -Dvolatile= DNAGroup.h DNAVisGroup.h DNANode.h DNAProp.h DNASign.h DNASignBaseline.h DNASignGraphic.h DNAFlatBuilding.h DNAWall.h DNAWindows.h DNACornice.h DNALandmarkBuilding.h DNAAnimProp.h DNAInteractiveProp.h DNAAnimBuilding.h DNADoor.h DNAFlatDoor.h DNAStreet.h DNABattleCell.h
make[2]: *** [liblibpandadna.dylib] Error 133
make[1]: *** [CMakeFiles/libpandadna.dir/all] Error 2
make: *** [all] Error 2

**Comment by loblao** [comment]
Please check if interrogate runs on non-libpandadna context. The issue might be related to your Panda build.
