### ISSUE TITLE
cmake fails on mac osx el capitan

### ISSUE THREAD

**Issue by mgracer48** [loblao/libpandadna#40]
config_dna.h:27:34: error: syntax error, unexp
ected ','
NotifyCategoryDecl(dna, EXPCL_DNA, EXPTP_DNA);
                                 ^
Error parsing file: 'config_dna.h'

Interrogating base

The following command return a non-zero value (1): /Developer/Panda3D/bin/interrogate -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus -fnames -string -refcount -assert -S /Developer/Panda3D/include/parser-inc -S /Developer/Panda3D/include -I /Developer/Panda3D/include -I/Users/mgracer48/Downloads/libpandadna-master/src/base -I/Users/mgracer48/Downloads/libpandadna-master/src/suit -I/Users/mgracer48/Downloads/libpandadna-master/src/components -srcdir /Users/mgracer48/Downloads/libpandadna-master/src/base -oc /Users/mgracer48/Downloads/libpandadna-master/src/base_igate.cxx -od /Users/mgracer48/Downloads/libpandadna-master/src/base.in -python-native -DCPPPARSER -D__STDC__=1 -D__cplusplus -D__inline -longlong __int64 -D_X86_ -DWIN32_VC -DWIN32 -module libpandadna -library base -Dvolatile= config_dna.h dnabase.h DNALoader.h DNAStorage.h

libp3interrogatedb found
Configuring done
CMake Error at CMakeLists.txt:144 (add_library):
  Cannot find source file:

    src/base_igate.cxx

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: libpandadna
CMake Error: Cannot determine link language for target "libpandadna".
Generating done

**Comment by loblao** [comment]
Update your Panda3D.
