### ISSUE TITLE
mac osx fail to build libpandadna

### ISSUE THREAD

**Issue by mgracer48** [loblao/libpandadna#41]
MacBook-Pro-2:build mgracer48$ make 
[  3%] Building CXX object CMakeFiles/libpandadna.dir/src/base/DNALoader.cxx.o
[  6%] Building CXX object CMakeFiles/libpandadna.dir/src/base/DNAStorage.cxx.o
[  9%] Building CXX object CMakeFiles/libpandadna.dir/src/base/config_dna.cxx.o
/Users/mgracer48/Downloads/libpandadna-master/src/base/config_dna.cxx:31:1: error: 
      duplicate explicit instantiation of
      'NotifyCategoryProxy<NotifyCategoryGetCategory_dna>'
NotifyCategoryDef(dna, "");
^
/Developer/Panda3D/include/notifyCategoryProxy.h:176:3: note: expanded from
      macro 'NotifyCategoryDef'
  NotifyCategoryDefName(basename, #basename, parent_category);
  ^
/Developer/Panda3D/include/notifyCategoryProxy.h:164:18: note: expanded from
      macro 'NotifyCategoryDefName'
  template class NotifyCategoryProxy<NotifyCategoryGetCategory_ ## basename>; \
                 ^
/Users/mgracer48/Downloads/libpandadna-master/src/base/config_dna.h:27:1: note: 
      previous explicit instantiation is here
NotifyCategoryDecl(dna, EXPCL_DNA, EXPTP_DNA);
^
/Developer/Panda3D/include/notifyCategoryProxy.h:137:39: note: expanded from
      macro 'NotifyCategoryDecl'
  EXPORT_TEMPLATE_CLASS(expcl, exptp, NotifyCategoryProxy<NotifyCategory...
                                      ^
/Developer/Panda3D/include/dtoolbase_cc.h:199:30: note: expanded from macro
      'EXPORT_TEMPLATE_CLASS'
  exptp template class expcl classname;
                             ^
1 error generated.
make[2]: *** [CMakeFiles/libpandadna.dir/src/base/config_dna.cxx.o] Error 1
make[1]: *** [CMakeFiles/libpandadna.dir/all] Error 2
make: *** [all] Error 2
MacBook-Pro-2:build mgracer48$

**Comment by mgracer48** [comment]
stupid java c++ errors

**Comment by Wilee999** [comment]
yeah c++ is a ripoff of java

**Comment by Loudrob** [comment]
java and c++ merged together recently

**Comment by roke-william** [comment]
pro
