### ISSUE TITLE
cannot be run on a game with toontown source(mac)

### ISSUE THREAD

**Issue by mgracer48** [loblao/libpandadna#52]
Invalid TypeHandle index 220!  Is memory corrupt?
Assertion failed: (pnode != (TypeRegistryNode *)NULL), function record_derivation, file dtool/src/dtoolbase/typeRegistry.cxx, line 160.

**Comment by s0r00t** [comment]
We need more information to diagnose the bug. Which source? Which OS? Can you provide us with a more complete log?

**Comment by mgracer48** [comment]
Thats as complete as it gets and i use el capitan

Um toontown empire source find it on my profile checkout libpandadna branch
