### ISSUE TITLE
how to load?

### ISSUE THREAD

**Issue by UnknownProjecter** [loblao/libpandadna#55]
I'm having a hard time. Can you explain where exactly the .DNA file has to go to? Thanks!

**Comment by masterbate** [comment]
In the trash folder of your computer, delete it all and it'll be in ram and ready to decrypt base64 sha

**Comment by UnknownProjecter** [comment]
how do you use this?  Idk what that is tbh

**Comment by mfwass** [comment]
Issues on GitHub are not for usage support.  Please refer to documentation provided.
