### ISSUE TITLE
Segfault 11 in nirai compiled game (macos 10.11)

### ISSUE THREAD

**Issue by lolman8776** [loblao/libpandadna#58]
I'm still not sure whether this is a Nirai or Libpandadna issue, but I'll post it here just to be safe:

When loading DNA files, my game (compiled with Nirai) will get a segmentation fault 11 and crash. I don't know what else to say about it, because I also don't know much about this type of error.

**Comment by mfwass** [comment]
Get a backtrace using gdb.

**Comment by lolman8776** [comment]
How do I do that?

**Comment by lolman8776** [comment]
I don't know if this is helpful or not. I ran gdb and did the following commands: `target exec ./rebuilt` `run` `backtrace` in that order.

Here's what the backtrace command told me:
```
#0  0x0000000100645c10 in ?? ()
#1  0x0000000107773ff8 in ?? ()
#2  0x0000000107773f20 in ?? ()
#3  0x000000010390a110 in ?? ()
#4  0x0000000101d95460 in ?? ()
#5  0x00007fff5fbeff68 in ?? ()
#6  0x00000001077736d0 in ?? ()
#7  0x00007fff5fbefce0 in ?? ()
#8  0x0000000100648962 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by mfwass** [comment]
Spoke with a few others, they do not think this is Nirai or libpandadna specific.  Rather, this is an issue on your end.

Also, it's worth saying that **Nirai is *not* Toontown**.  It's not our problem if Toontown doesn't work on Nirai, we're not in the business of helping other private servers compete with TTR.

There is no reason for _yet another_ Toontown private server.  If you want to play TT, check out [Toontown Rewritten](https://toontownrewritten.com/).

ProTip™:  If you're going to say "_I want to learn how to program_" like most people do when it comes to making a Toontown private server, stick to something smaller.  A MMO is a massive project (it's even in its name!! "massively") -- and is incredibly difficult to maintain.  For the sanity of yourself and everyone else in the TT community, just play TTR and call it a day.

</end rant>
