### ISSUE TITLE
[cxx-parser] getSuitPath always fails on Sellbot Factory exterior, Cashbot and Lawbot HQ files.

### ISSUE THREAD

**Issue by LittleToonCat** [loblao/libpandadna#61]
When reading the original TTO DNA files for the three locations (zones: 11200, 12000, 13000),  assigned SuitPlanners appears to be failing to spawn any cogs in those areas, with them printing out a "Couldn't get a destination" message when notify level for it is set to debug, leaving the player with empty areas.

This issue may have something to do with the recent rewrite that occured in https://github.com/loblao/libpandadna/commit/bdcccd69ae488f8e310a31224cab4a45ce941e64, because when set to debug, the function results in an spam of "path is too short", or "path not found" messages.

**Comment by jwcotejr** [comment]
Indeed, https://github.com/loblao/libpandadna/commit/bdcccd69ae488f8e310a31224cab4a45ce941e64 introduces this issue. Investigating.

**Comment by jwcotejr** [comment]
Let me know if this fix works for you.
