### ISSUE TITLE
Latest Ply broker the script

### ISSUE THREAD

**Issue by CrankySupertoon** [loblao/libpandadna#65]
![70EE53CC-3F17-4594-8B71-FF3AC9494085](https://user-images.githubusercontent.com/48419040/57078836-0af5a400-6cbd-11e9-8508-3f9dad6ce34a.png)

**Comment by pythonengineer** [comment]
The libpandadna compiler currently only supports Python 2. Judging by the SyntaxError, you're attempting to run it using Python 3.

**Comment by CrankySupertoon** [comment]
I’m pretty sure it’s python 3 atleast running python spits out pyrhin 2.7

**Comment by pythonengineer** [comment]
I'm not sure what to tell you, that SyntaxError is specific to the Python 3 interpreter, as well as the ModuleNotFoundError, although you would get the same error in the form of an ImportError w/ the Python 2 interpreter. You can try changing your PATH to a Python 2 installation to be able to have `python` in the command line point to it.

**Comment by MacandWindows** [comment]
sorry lag

**Comment by MacandWindows** [comment]
> pyrhin

that's a very tricky issue it seems
