### ISSUE TITLE
How to compile on Windows?

### ISSUE THREAD

**Issue by CrankySupertoon** [loblao/libpandadna#67]
Can you provide a guide

**Comment by pythonengineer** [comment]
Clone the repository and run CMake. Set the PANDA_DIR CMake option to the directory of your Panda3D installation. CMake should automatically run interrogate on the libpandadna components, and then generate Visual Studio build files according to the Visual Studio version you use (you can specify this). You can then run Visual Studio and build libpandadna, which will link it and create a `libpandadna.pyd` file.

This is a brief run-down, but there isn't a more formal guide to my knowledge right now.

**Comment by pythonengineer** [comment]
Closing, I provided a simple guide above 10 months ago (and GitHub issues aren't for assistance in usage).
